### PR TITLE
Update VNET feature branch

### PR DESCRIPTION
**Pull request by emlyn**
- bring it up to date with master
- adapt secrets.yaml format as discussed in #256 
- support service principal auth for storage account

I think there's still a bit of cleaning up and error checking remaining, but it would be good to get feedback on what's here so far.

### CODE REVIEW

**Comment by emlyn** [comment]
I've added some checks so that it fails if both service principal and shared key auth is provided for either batch or storage. What other checks/validation do you think are needed? (for easy reference, this is how it compares to master: https://github.com/Azure/aztk/compare/89f0e54...emlyn:vnet).

**Comment by emlyn** [comment]
I've also added some checks that the correct servicePrincipal keys are present.
One issue I'm not sure about, is that I currently hard code the resource url for service principal credentials (`'https://management.core.windows.net/'` / `'https://batch.core.windows.net/'`). Is there a way to get the correct values programmatically, or should there be a way for the user to specify these?

**Comment by emlyn** [comment]
@jafreck @paselem Happy New Year! Is this OK to merge into the feature branch now?

**Comment by jafreck** [comment]
@emlyn yeah this is fine to merge. We will do a final review before merging into master which might include some small changes like variable/yaml key renames. But everything else looks great!

**Comment by emlyn** [comment]
@jafreck Thanks. don't think I have permission to merge, could you (or someone else with permission) do it please?

**Comment by jafreck** [comment]
@emlyn Sorry -- didn't realize that. I'll take care of it.

**Comment by emlyn** [comment]
What's the next step, shall I open a PR from the feature branch onto master? It's already a bit behind again, so there are other things showing up in the diff - maybe it's better if someone with appropriate access merges master in first?

**Comment by paselem** [comment]
@jafreck - can you handle the merge when you get a chance? Probably worth doing it now. I wanted to take some time to test this branch out too since it's a pretty big change.

@emlyn - have you had a chance to do much testing on this yet?

**Comment by emlyn** [comment]
@paselem I've successfully used it to start a couple of clusters and run a few spark jobs, but haven't done any thorough testing.

**Comment by paselem** [comment]
Thanks for the update @emlyn. We have another huge change being worked on in parallel for 'serverless jobs', and we are kind of in the same position. Lots of ad-hoc testing, but not enough thorough testing. I think we need to start to seriously think about having good automated tests especially for very large changes like this one.

We have a sync up today to discuss immediate next steps for this project - specifically how do we get the 'serverless jobs' and 'vnet' branches merged into master and released. My main concern is around the amount of churn and testing, so we'll need to get that addressed before we can be confident about the quality of the feature going in. I'm hopeful that by the end of the day we'll have a plan down to getting this merged in and can move forward. I'll update this thread once we know more.

**Comment by paselem** [comment]
@emlyn - we discussed these changes today. I did some quick testing and so far things look good. I have a local change w/ master merged into it and will probably push that back into this branch soon. We agreed that we want to push this into master by the end of the week. @jafreck has signed off and @timotheeguerin will do some additional testing and reviews. We need to figure out which change will go into master first (this or the serverless jobs). If we sign off on this quickly my guess is that this will make it in sooner.

**Pull request merged**
